[source]
name = "pencil"
nphotons = 100000
direction = "z"
position = [0.0,0.0,-10.0]
spectrum_type = "constant"
wavelength = 500.0

[grid]
nxg = 500
nyg = 500
nzg = 500
xmax = 50.0
ymax = 50.0
zmax = 0.015

[geometry]
geom_name = "cuvette"
innerCuvetteDimensions = [8.0,8.0,8.0]
outerCuvetteDimensions = [9.0,9.0,9.0]
BoxDimensions = [100.0,100.0,0.02]
boundingBox = [10.0,10.0,10.0]
position = [0.0,0.0,0.0]
mus = [5.0]
mua = [20.0]
hgg = [0.75]
n = [1.2]

[inverse]
maxStepSize = 1
gradStepSize = 0.0005
accuracy = 0.001
maxNumSteps = 2000
Findmus = true
Findmua = true
Findg = true
Findn = true
musUpper = 79.0
musLower = 76.0
muaUpper = 37.0
muaLower = 35.0
hggUpper = 0.70
hggLower = 0.5
nUpper = 70.0
nLower = 42.0
layer = 1

[symmetry]
symmetryType = "360rotational"
escapenphotons = 100000
GridSize = [100,500,200]
maxValues = [60.0, 360.0, 30.0]
position = [0.0,0.0,0.0]
direction = [1.0,0.0,0.0]
rotation = 0

[[detectors]]
type="circle"
ID = "this is a test"
position=[0.0, 0.0, -0.01]
direction=[0.0, 0.0, -1.0]
radius= 5
nbins=100
maxval = 1.0
trackHistory=false
inverseTarget = 6.06E-06

[[detectors]]
type="circle"
ID = "1"
position=[0.0, 0.0, 0.01]
direction=[0.0, 0.0, 1.0]
radius=5
nbins=100
maxval = 1.0
trackHistory=false
inverseTarget = 0.104622437

[[detectors]]
type="circle"
ID = "2"
position=[0.0, 0.01, 0.0]
direction=[0.0, 1.0, 0.0]
radius=5
nbins=100
maxval = 1.0
trackHistory=false
inverseTarget = 0.108356081

[[detectors]]
type="circle"
ID = "3"
position=[0.0, 0.01, 0.01]
direction=[0.0, 1.0, 1.0]
radius=5
nbins=100
maxval = 1.0
trackHistory=false
inverseTarget = 0.065549636

[[detectors]]
type="circle"
ID = "4"
position=[0.0, 0.01, -0.01]
direction=[0.0, 1.0, -1.0]
radius=5
nbins=100
maxval = 1.0
trackHistory=false
inverseTarget = 0.062327753

[output]
fluence = "fluence.nrrd"
render_geometry_name = "geom_render.nrrd"
render_geometry = true
render_source_name = "source_render.nrrd"
render_source = true
render_size = [200,200,200]
overwrite = true

[simulation]
iseed = 321321354
absorb=true
load_checkpoint=false
checkpoint_file="check.ckpt"
checkpoint_every_n=10000