[source]
name = "pencil"
nphotons = 1000000
position = [-25.0,0.0,0.0]
direction = "x"


[grid]
nxg = 200
nyg = 110
nzg = 100
xmax = 30.0
ymax = 31.0
zmax = 32.0

[geometry]
geom_name = "box"
boundingBox = [60.0,62.0,64.0]
BoxDimensions = [50.0,62.0,64.0]
mus = [1.0]
mua = [0.0]
g = [0.0]
n = [1.0]


[symmetry]
symmetryType = "360rotational"
escapenphotons = 100000
GridSize = [100,500,200]
maxValues = [60.0, 360.0, 30.0]
position = [0.0,0.0,0.0]
direction = [1.0,0.0,0.0]
rotation = 0

[[detectors]]
type="annulus"
ID = "Offset1mm"
position=[-25.0, 0.0, 0.0]
direction=[-1.0, 0.0, 0.0]
radius1 = 0.0
radius2 = 1.0
nbins = 10
maxval = 2.0
trackHistory = false

[[detectors]]
type="annulus"
ID = "Offset2mm"
position=[-25.0, 0.0, 0.0]
direction=[-1.0, 0.0, 0.0]
radius1 = 1.0
radius2 = 2.0
nbins = 10
maxval = 2.0
trackHistory = false

[[detectors]]
type="annulus"
ID = "Offset3mm"
position=[-25.0, 0.0, 0.0]
direction=[-1.0, 0.0, 0.0]
radius1 = 2.0
radius2 = 3.0
nbins = 10
maxval = 2.0
trackHistory = false

[[detectors]]
type="annulus"
ID = "Offset4mm"
position=[-25.0, 0.0, 0.0]
direction=[-1.0, 0.0, 0.0]
radius1 = 3.0
radius2 = 4.0
nbins = 10
maxval = 2.0
trackHistory = false

[[detectors]]
type="annulus"
ID = "Offset5mm"
position=[-25.0, 0.0, 0.0]
direction=[-1.0, 0.0, 0.0]
radius1 = 4.0
radius2 = 5.0
nbins = 10
maxval = 2.0
trackHistory = false

[[detectors]]
type="annulus"
ID = "Offset6mm"
position=[-25.0, 0.0, 0.0]
direction=[-1.0, 0.0, 0.0]
radius1 = 5.0
radius2 = 6.0
nbins = 10
maxval = 2.0
trackHistory = false

[[detectors]]
type="annulus"
ID = "Offset7mm"
position=[-25.0, 0.0, 0.0]
direction=[-1.0, 0.0, 0.0]
radius1 = 6.0
radius2 = 7.0
nbins = 10
maxval = 2.0
trackHistory = false

[[detectors]]
type="annulus"
ID = "Offset8mm"
position=[-25.0, 0.0, 0.0]
direction=[-1.0, 0.0, 0.0]
radius1 = 7.0
radius2 = 8.0
nbins = 10
maxval = 2.0
trackHistory = false

[[detectors]]
type="annulus"
ID = "Offset9mm"
position=[-25.0, 0.0, 0.0]
direction=[-1.0, 0.0, 0.0]
radius1 = 8.0
radius2 = 9.0
nbins = 10
maxval = 2.0
trackHistory = false

[[detectors]]
type="annulus"
ID = "Offset10mm"
position=[-25.0, 0.0, 0.0]
direction=[-1.0, 0.0, 0.0]
radius1 = 9.0
radius2 = 10.0
nbins = 10
maxval = 2.0
trackHistory = false

[[detectors]]
type="annulus"
ID = "Offset11mm"
position=[-25.0, 0.0, 0.0]
direction=[-1.0, 0.0, 0.0]
radius1 = 10.0
radius2 = 11.0
nbins = 10
maxval = 2.0
trackHistory = false


[output]
fluence = "fluence.nrrd"
render_geometry_name = "geom_render.nrrd"
render_geometry = true
render_source_name = "source_render.nrrd"
render_source = true
render_size = [200,200,200]
overwrite = true

[simulation]
iseed = 123456789
absorb=true
load_checkpoint=false
checkpoint_file="check.ckpt"
checkpoint_every_n=10000