[source]
name = "pencil"
nphotons = 100000
direction = "z"
position = [0.0,0.0,-1.0]
spectrum_type = "constant"
wavelength = 500.0

[grid]
nxg = 500
nyg = 500
nzg = 500
xmax = 2.5
ymax = 2.5
zmax = 2.5

[geometry]
geom_name = "box"
numOptProp = 1
innerCuvetteDimensions = [1.0,1.0,1.0]
outerCuvetteDimensions = [1.25,1.25,1.25]
BoxDimensions = [1.0,1.0,1.0]
boundingBox = [5.0,5.0,5.0]
position = [0.0,0.0,0.0]
mus = [5.0]
mua = [5.0]
hgg = [0.4]
n = [1.2]

[inverse]
maxStepSize = 1
gradStepSize = 0.0005
accuracy = 0.001
maxNumSteps = 1000
Findmus = true
Findmua = false
Findg = true
Findn = false
ReducedmusGuessing = true
musUpper = 100.0
musLower = 30.0
muaUpper = 100.0
muaLower = 0.0
hggUpper = 1.0
hggLower = 0.0
nUpper = 5.0
nLower = 1.0
reducedmusUpper = 31.0
reducedmusLower = 28.0
layer = 1

[symmetry]
symmetryType = "360rotational"
escapenphotons = 100000
GridSize = [100,500,200]
maxValues = [60.0, 360.0, 30.0]
position = [0.0,0.0,0.0]
direction = [1.0,0.0,0.0]
rotation = 0

[[detectors]]
type="circle"
ID = "this is a test"
position=[0.0, 0.0, -1.414213562]
direction=[0.0, 0.0, -1.0]
radius= 1
nbins=100
maxval = 1.0
trackHistory=false
inverseTarget = 0.136278311




[[detectors]]
type="circle"
ID = "2"
position=[0.0, 1.414213562, 0.0]
direction=[0.0, 1.0, 0.0]
radius=1
nbins=100
maxval = 1.0
trackHistory=false
inverseTarget = 0.002608717	




[[detectors]]
type="circle"
ID = "4"
position=[0.0, 1.0, -1.0]
direction=[0.0, 1.0, -1.0]
radius=1
nbins=100
maxval = 1.0
trackHistory=false
inverseTarget = 0.066143302


[output]
fluence = "fluence.nrrd"
render_geometry_name = "geom_render.nrrd"
render_geometry = true
render_source_name = "source_render.nrrd"
render_source = true
render_size = [200,200,200]
overwrite = true

[simulation]
iseed = 321321359
absorb=true
load_checkpoint=false
checkpoint_file="check.ckpt"
checkpoint_every_n=10000