[source]
name = "annulus"
nphotons = 10000000
position = [0.0, 0.0, -10.0]
rotation = [0.0,0.0,1.0]
focalLength = 10.0
rhi = 1.2
rlo = 1.0
spectrum_type = "constant"
wavelength = 500.0

[grid]
nxg = 200
nyg = 200
nzg = 200
xmax = 10
ymax = 10
zmax = 10

[geometry]
geom_name = "exp"
musb = 0.001 # bottle scattering
muab = 0.000001 # bottle absorb
musc = 0.1 # contents scattering
muac = 0.0001 # contents absorb
hgg = 0.9

[output]
fluence = "fluence.nrrd"
render_geometry_name = "geom_render.nrrd"
render_geometry = true
render_source_name = "source_render.nrrd"
render_source = true
render_size = [200,200,200]
overwrite = true

[simulation]
iseed = 123456789