[source]
name = "circular"
nphotons = 100000
direction = "z"
position = [0.0,0.0,-10.0]
spectrum_type = "constant"
wavelength = 500.0
radius = 3.15

[grid]
nxg = 250
nyg = 250
nzg = 250
xmax = 25.0
ymax = 25.0
zmax = 25.0

[geometry]
geom_name = "box"
numOptProp = 1
BoxDimensions = [50.0,50.0,0.35]
boundingBox = [50.0,50.0,50.0]
position = [0.0,0.0,0.0]
mus = [35.0]
mua = [1.2]
hgg = [0.0]
n = [1.6493]

[inverse]
maxStepSize = 1
gradStepSize = 0.0005
accuracy = 0.00001
maxNumSteps = 1000
Findmus = true
Findmua = true
Findg = false
Findn = false
ReducedmusGuessing = false
musUpper = 59.0
musLower = 37.0
muaUpper = 0.65
muaLower = 0.37
hggUpper = 1.0
hggLower = 0.0
nUpper = 5.0
nLower = 1.0
reducedmusUpper = 21.1
reducedmusLower = 20.9
layer = 1


[[detectors]]
type="circle"
ID = "Transmitted"
position=[0.0, 0.0, 1.0]
direction=[0.0, 0.0, 1.0]
radius= 100.0
nbins = 100
maxval = 100.0
trackHistory=false
inverseTarget = 0.034145699
acceptanceAngle = 88.0

[[detectors]]
type="circle"
ID = "Reflected"
position=[0.0, 0.0, -1.0]
direction=[0.0, 0.0, -1.0]
radius= 100.0
nbins = 100
maxval = 100.0
trackHistory=false
inverseTarget = 0.537282145
acceptanceAngle = 88.0

[output]
fluence = "fluence.nrrd"
render_geometry_name = "geom_render.nrrd"
render_geometry = true
render_source_name = "source_render.nrrd"
render_source = true
render_size = [200,200,200]
overwrite = true

[simulation]
iseed = 32132135
absorb=true
load_checkpoint=false
checkpoint_file="check.ckpt"
checkpoint_every_n=10000