[source]
name = "focus"
nphotons = 1000000
position = [0.0,0.0,0.0]
spectrum_type = "constant"
direction = "x"
focalLength = 1.0
beam_size = 0.5
focus_type = "circle"

[grid]
nxg = 200
nyg = 200
nzg = 200
xmax = 1.0
ymax = 1.0
zmax = 1.0

[geometry]
geom_name = "sphere"
boundingBox = [2.0,2.0,2.0]
sphereRadius = 1.0
position = [0.0,0.0,0.0]
numOptProp = 1
mus = [10.0]

[output]
fluence = "fluence.nrrd"
render_geometry_name = "geom_render.nrrd"
render_geometry = true
render_source_name = "source_render.nrrd"
render_source = true
render_size = [250,250,250]
overwrite = true

[simulation]
iseed = 123456789
absorb=true
load_checkpoint=false
checkpoint_file="check.ckpt"
checkpoint_every_n=10000