[source]
name = "pencil"
nphotons = 100000
position = [0.0,0.0,1.0]
rotation = [0.0,0.0,-1.0]
direction
focalLength = 1.0
spectrum_type = "constant"
wavelength = 500.0

[grid]
nxg = 500
nyg = 500
nzg = 500
xmax = 1.0
ymax = 1.0
zmax = 1.0

[geometry]
geom_name = "box"
BoxDimensions = [2.0,2.0,2.0]

[output]
fluence = "fluence.nrrd"
render_geometry_name = "geom_render.nrrd"
render_geomerty = true
render_source_name = "source_render.nrrd"
render_source = true
render_size = [200,200,200]
overwrite = true

[simulation]
iseed = 123456789
absorb=true
load_checkpoint=false
checkpoint_file="check.ckpt"
checkpoint_every_n=10000