[source]
name = "pencil"
nphotons = 1000000
direction = "z"
position = [0.0,0.0,-1.0]
spectrum_type = "constant"
wavelength = 500.0

[grid]
nxg = 500
nyg = 500
nzg = 500
xmax = 50.0
ymax = 50.0
zmax = 1.5

[geometry]
geom_name = "box"
BoxDimensions = [100.0,100.0,2.0]
boundingBox = [100.0,100.0,3.0]
mus = [0.9]
hgg = [0.75]
mua = [0.1]

[[detectors]]
type="circle"
position=[0.0, 0.0, -1.101]
direction=[0.0, 0.0, -1.0]
radius1=20
nbins=100
maxval = 1.0
trackHistory=false

[[detectors]]
type="circle"
position=[0.0, 0.0, +1.001]
direction=[0.0, 0.0, +1.0]
radius1=100
nbins=100
maxval = 1.0
trackHistory=false

[output]
fluence = "fluence.nrrd"
render_geometry_name = "geom_render.nrrd"
render_geomerty = true
render_source_name = "source_render.nrrd"
render_source = true
render_size = [200,200,200]
overwrite = true

[simulation]
iseed = 123456789
absorb=true
load_checkpoint=false
checkpoint_file="check.ckpt"
checkpoint_every_n=10000