[source]
name = "circular"
nphotons = 100000000
direction = "z"
position = [0.0,0.0,-25.0]
rotation = [0.0,0.0,0.0]
radius = 0.001
spectrum_type = "constant"
wavelength = 500.0

[grid]
nxg = 500
nyg = 500
nzg = 500
xmax = 25.0
ymax = 25.0
zmax = 25.0

[geometry]
geom_name = "box"
numOptProp = 1
BoxDimensions = [48.0,48.0,48.0]
boundingBox = [50.0,50.0,50.0]
position = [0.0,0.0,0.0]
mus = [5.0]
mua = [0.000001]
hgg = [0.0]
n = [1.0]


[symmetry]
symmetryType = "adjoint"
escapenphotons = 10000000
GridSize = [50,360,100]
maxValues = [24.0, 360.0, 24.0]
position = [0.0,0.0,0.0]
direction = [0.0,1.0,0.0]
rotation = 0.0

[[detectors]]
type="annulus"
ID = "0.5mm"
position=[0.0, 0.0, -24.00001]
direction=[0.0, 0.0, -1.0]
radius1 = 0.0
radius2 = 1.0
nbins=100
maxval = 100.0
trackHistory=false

[[detectors]]
type="annulus"
ID = "1.5mm"
position=[0.0, 0.0, -24.00001]
direction=[0.0, 0.0, -1.0]
radius1 = 1.0
radius2 = 2.0
nbins=100
maxval = 100.0
trackHistory=false

[[detectors]]
type="annulus"
ID = "2.5mm"
position=[0.0, 0.0, -24.00001]
direction=[0.0, 0.0, -1.0]
radius1 = 2.0
radius2 = 3.0
nbins=100
maxval = 100.0
trackHistory=false

[[detectors]]
type="annulus"
ID = "3.5mm"
position=[0.0, 0.0, -24.00001]
direction=[0.0, 0.0, -1.0]
radius1 = 3.0
radius2 = 4.0
nbins=100
maxval = 100.0
trackHistory=false

[[detectors]]
type="annulus"
ID = "4.5mm"
position=[0.0, 0.0, -24.00001]
direction=[0.0, 0.0, -1.0]
radius1 = 4.0
radius2 = 5.0
nbins=100
maxval = 100.0
trackHistory=false

[[detectors]]
type="annulus"
ID = "5.5mm"
position=[0.0, 0.0, -24.00001]
direction=[0.0, 0.0, -1.0]
radius1 = 5.0
radius2 = 6.0
nbins=100
maxval = 100.0
trackHistory=false

[[detectors]]
type="annulus"
ID = "6.5mm"
position=[0.0, 0.0, -24.00001]
direction=[0.0, 0.0, -1.0]
radius1 = 6.0
radius2 = 7.0
nbins=100
maxval = 100.0
trackHistory=false

[[detectors]]
type="annulus"
ID = "7.5mm"
position=[0.0, 0.0, -24.00001]
direction=[0.0, 0.0, -1.0]
radius1 = 7.0
radius2 = 8.0
nbins=100
maxval = 100.0
trackHistory=false
	
[[detectors]]
type="annulus"
ID = "8.5mm"
position=[0.0, 0.0, -24.00001]
direction=[0.0, 0.0, -1.0]
radius1 = 8.0
radius2 = 9.0
nbins=100
maxval = 100.0
trackHistory=false

[[detectors]]
type="annulus"
ID = "9.5mm"
position=[0.0, 0.0, -24.00001]
direction=[0.0, 0.0, -1.0]
radius1 = 9.0
radius2 = 10.0
nbins=100
maxval = 100.0
trackHistory=false

[[detectors]]
type="annulus"
ID = "10.5mm"
position=[0.0, 0.0, -24.00001]
direction=[0.0, 0.0, -1.0]
radius1 = 10.0
radius2 = 11.0
nbins=100
maxval = 100.0
trackHistory=false


[output]
fluence = "fluence.nrrd"
render_geometry_name = "geom_render.nrrd"
render_geometry = true
render_source_name = "source_render.nrrd"
render_source = true
render_size = [200,200,200]
overwrite = true

[simulation]
iseed = 32132135
absorb=true
load_checkpoint=false
checkpoint_file="check.ckpt"
checkpoint_every_n=10000