[source]
name = "uniform"
nphotons = 1000000
direction = "-z"
point1 = [ -5.0, -5.0, 2.0]
point2 = [ 10.0, 0.0, 0.0]
point3 = [ 0.0, 10.0, 0.0]
spectrum_type = "constant"
wavelength = 500.0

[grid]
nxg = 250
nyg = 250
nzg = 1000
xmax = 50.0
ymax = 50.0
zmax = 2.0

[geometry]
geom_name = "box"
BoxDimensions = [100.0,100.0,3.9]
boundingBox = [100.0,100.0,4.0]
position = [0.0,0.0,0.0]
mus = [210]
hgg = [0.9]
mua = [0.23]
n = [1.38]

[output]
fluence = "fluence.nrrd"
render_geometry_name = "geom_render.nrrd"
render_geometry = true
render_source_name = "source_render.nrrd"
render_source = true
render_size = [200,200,200]
overwrite = true

[simulation]
iseed = 123456789
absorb=true
load_checkpoint=false
checkpoint_file="check.ckpt"
checkpoint_every_n=10000