[source]
name = "circular"
nphotons = 100000
direction = "z"
position = [0.0,0.0,-10.0]
spectrum_type = "constant"
wavelength = 500.0
radius = 3.15

[grid]
nxg = 250
nyg = 250
nzg = 250
xmax = 25.0
ymax = 25.0
zmax = 25.0

[geometry]
geom_name = "box"
numOptProp = 1
BoxDimensions = [50.0,50.0,0.35]
boundingBox = [50.0,50.0,50.0]
position = [0.0,0.0,0.0]
mus = [56.0174]
mua = [0.61975]
hgg = [0.0]
n = [1.6425]

[inverse]
maxStepSize = 1
gradStepSize = 0.0005
accuracy = 0.001
maxNumSteps = 1000
Findmus = true
Findmua = true
Findg = false
Findn = false
ReducedmusGuessing = false
MueffGuessing = true
musUpper = 100.0
musLower = 20.0
muaUpper = 1.4
muaLower = 0.0
hggUpper = 1.0
hggLower = 0.0
nUpper = 5.0
nLower = 1.0
reducedmusUpper = 66.0
reducedmusLower = 52.0
mueffUpper = 9.9
mueffLower = 8.0
layer = 1


[[detectors]]
type="circle"
ID = "Angle330"
position=[0.0, -5.275, 9.137]
direction=[0.0, -0.500, 0.866]
radius= 4.75
nbins = 100
maxval = 4.75
trackHistory=false
inverseTarget = 0.001535165
acceptanceAngle = 15.0

[[detectors]]
type="circle"
ID = "Angle340"
position=[0.0, -3.608, 9.914]
direction=[0.0, -0.342, 0.940]
radius= 4.75
nbins = 100
maxval = 4.75
trackHistory=false
inverseTarget = 0.001688462
acceptanceAngle = 15.0

[[detectors]]
type="circle"
ID = "Angle350"
position=[0.0, -1.832, 10.390]
direction=[0.0, -0.174, 0.985]
radius= 4.75
nbins = 100
maxval = 4.75
trackHistory=false
inverseTarget = 0.001784615
acceptanceAngle = 15.0

[[detectors]]
type="circle"
ID = "Angle000"
position=[0.0, 0.000, 10.550]
direction=[0.0, 0.000, 1.000]
radius= 4.75
nbins = 100
maxval = 4.75
trackHistory=false
inverseTarget = 0.001824451
acceptanceAngle = 15.0

[[detectors]]
type="circle"
ID = "Angle010"
position=[0.0, 1.832, 10.390]
direction=[0.0, 0.174, 0.985]
radius= 4.75
nbins = 100
maxval = 4.75
trackHistory=false
inverseTarget = 0.001797527
acceptanceAngle = 15.0

[[detectors]]
type="circle"
ID = "Angle020"
position=[0.0, 3.608, 9.914]
direction=[0.0, 0.342, 0.940]
radius= 4.75
nbins = 100
maxval = 4.75
trackHistory=false
inverseTarget = 0.001693132
acceptanceAngle = 15.0

[[detectors]]
type="circle"
ID = "Angle030"
position=[0.0, 5.275, 9.137]
direction=[0.0, 0.500, 0.866]
radius= 4.75
nbins = 100
maxval = 4.75
trackHistory=false
inverseTarget = 0.001524451
acceptanceAngle = 15.0


[output]
fluence = "fluence.nrrd"
render_geometry_name = "geom_render.nrrd"
render_geometry = true
render_source_name = "source_render.nrrd"
render_source = true
render_size = [200,200,200]
overwrite = true

[simulation]
iseed = 32132135
absorb=true
load_checkpoint=false
checkpoint_file="check.ckpt"
checkpoint_every_n=10000